apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: onboarding
spec:
  generators:
  - list:
      elements:
      - cluster: engineering-dev
        url: https://1.2.3.4
      - cluster: engineering-prod
        url: https://2.4.6.8
      - cluster: finance-preprod
        url: https://9.8.7.6
  - git:
      repoURL: https://github.com/tosmi-gitops/onboarding.git
      revision: HEAD
      directories:
      - path: tenants/*
  template:
    metadata:
      name: '{{path.basename}}-onboarding'
    spec:
      project: onboarding
      source:
        repoURL: https://github.com/tosmi-gitops/onboarding.git
        targetRevision: HEAD
        # path: tenants/{{path.basename}}{{cluster}}
                # path: tenants/{{path.basename}}{{cluster}}
      destination:
        server: '{{url}}'
        namespace: guestbook
